on:
    pull_request_target:
      branches-ignore:
        - 8.13

jobs:
    approve:
      name: Auto-approve docker push pr
      runs-on: ubuntu-latest
      if: |
        github.event.pull_request.user.login == 'ChristianeU'

      permissions:
        pull-requests: write
      steps:
        - uses: hmarr/auto-approve-action@v3